# Generated by Django 5.1.7 on 2025-03-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_remove_order_coffee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='coffee',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
