# Generated by Django 5.1.7 on 2025-03-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_rename_user_id_order_user_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
